'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { DdaAccordion as DdaAccordionElement, defineCustomElement as defineDdaAccordion } from "@dubai-design-system/components-js/dist/components/dda-accordion.js";
import { DdaAlert as DdaAlertElement, defineCustomElement as defineDdaAlert } from "@dubai-design-system/components-js/dist/components/dda-alert.js";
import { DdaAttachFile as DdaAttachFileElement, defineCustomElement as defineDdaAttachFile } from "@dubai-design-system/components-js/dist/components/dda-attach-file.js";
import { DdaAvatar as DdaAvatarElement, defineCustomElement as defineDdaAvatar } from "@dubai-design-system/components-js/dist/components/dda-avatar.js";
import { DdaBanner as DdaBannerElement, defineCustomElement as defineDdaBanner } from "@dubai-design-system/components-js/dist/components/dda-banner.js";
import { DdaBreadcrumb as DdaBreadcrumbElement, defineCustomElement as defineDdaBreadcrumb } from "@dubai-design-system/components-js/dist/components/dda-breadcrumb.js";
import { DdaButton as DdaButtonElement, defineCustomElement as defineDdaButton } from "@dubai-design-system/components-js/dist/components/dda-button.js";
import { DdaCheckbox as DdaCheckboxElement, defineCustomElement as defineDdaCheckbox } from "@dubai-design-system/components-js/dist/components/dda-checkbox.js";
import { DdaChip as DdaChipElement, defineCustomElement as defineDdaChip } from "@dubai-design-system/components-js/dist/components/dda-chip.js";
import { DdaCreditCard as DdaCreditCardElement, defineCustomElement as defineDdaCreditCard } from "@dubai-design-system/components-js/dist/components/dda-credit-card.js";
import { DdaCreditcardField as DdaCreditcardFieldElement, defineCustomElement as defineDdaCreditcardField } from "@dubai-design-system/components-js/dist/components/dda-creditcard-field.js";
import { DdaDropdown as DdaDropdownElement, defineCustomElement as defineDdaDropdown } from "@dubai-design-system/components-js/dist/components/dda-dropdown.js";
import { DdaFooter as DdaFooterElement, defineCustomElement as defineDdaFooter } from "@dubai-design-system/components-js/dist/components/dda-footer.js";
import { DdaHeader as DdaHeaderElement, defineCustomElement as defineDdaHeader } from "@dubai-design-system/components-js/dist/components/dda-header.js";
import { DdaHomeBanner as DdaHomeBannerElement, defineCustomElement as defineDdaHomeBanner } from "@dubai-design-system/components-js/dist/components/dda-home-banner.js";
import { DdaHorizontalStepper as DdaHorizontalStepperElement, defineCustomElement as defineDdaHorizontalStepper } from "@dubai-design-system/components-js/dist/components/dda-horizontal-stepper.js";
import { DdaInput as DdaInputElement, defineCustomElement as defineDdaInput } from "@dubai-design-system/components-js/dist/components/dda-input.js";
import { DdaLinkButton as DdaLinkButtonElement, defineCustomElement as defineDdaLinkButton } from "@dubai-design-system/components-js/dist/components/dda-link-button.js";
import { DdaNumberField as DdaNumberFieldElement, defineCustomElement as defineDdaNumberField } from "@dubai-design-system/components-js/dist/components/dda-number-field.js";
import { DdaPagination as DdaPaginationElement, defineCustomElement as defineDdaPagination } from "@dubai-design-system/components-js/dist/components/dda-pagination.js";
import { DdaPhonefield as DdaPhonefieldElement, defineCustomElement as defineDdaPhonefield } from "@dubai-design-system/components-js/dist/components/dda-phonefield.js";
import { DdaProgressbar as DdaProgressbarElement, defineCustomElement as defineDdaProgressbar } from "@dubai-design-system/components-js/dist/components/dda-progressbar.js";
import { DdaRadiobutton as DdaRadiobuttonElement, defineCustomElement as defineDdaRadiobutton } from "@dubai-design-system/components-js/dist/components/dda-radiobutton.js";
import { DdaRangeSlider as DdaRangeSliderElement, defineCustomElement as defineDdaRangeSlider } from "@dubai-design-system/components-js/dist/components/dda-range-slider.js";
import { DdaSearchInput as DdaSearchInputElement, defineCustomElement as defineDdaSearchInput } from "@dubai-design-system/components-js/dist/components/dda-search-input.js";
import { DdaSegmentedTabs as DdaSegmentedTabsElement, defineCustomElement as defineDdaSegmentedTabs } from "@dubai-design-system/components-js/dist/components/dda-segmented-tabs.js";
import { DdaSelect as DdaSelectElement, defineCustomElement as defineDdaSelect } from "@dubai-design-system/components-js/dist/components/dda-select.js";
import { DdaStickyFooter as DdaStickyFooterElement, defineCustomElement as defineDdaStickyFooter } from "@dubai-design-system/components-js/dist/components/dda-sticky-footer.js";
import { DdaTabs as DdaTabsElement, defineCustomElement as defineDdaTabs } from "@dubai-design-system/components-js/dist/components/dda-tabs.js";
import { DdaTextarea as DdaTextareaElement, defineCustomElement as defineDdaTextarea } from "@dubai-design-system/components-js/dist/components/dda-textarea.js";
import { DdaToggle as DdaToggleElement, defineCustomElement as defineDdaToggle } from "@dubai-design-system/components-js/dist/components/dda-toggle.js";
import { DdaTooltip as DdaTooltipElement, defineCustomElement as defineDdaTooltip } from "@dubai-design-system/components-js/dist/components/dda-tooltip.js";
import { DdaUiCard as DdaUiCardElement, defineCustomElement as defineDdaUiCard } from "@dubai-design-system/components-js/dist/components/dda-ui-card.js";
import { DdaVerticalStepper as DdaVerticalStepperElement, defineCustomElement as defineDdaVerticalStepper } from "@dubai-design-system/components-js/dist/components/dda-vertical-stepper.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type DdaAccordionEvents = NonNullable<unknown>;

export const DdaAccordion: StencilReactComponent<DdaAccordionElement, DdaAccordionEvents> = /*@__PURE__*/ createComponent<DdaAccordionElement, DdaAccordionEvents>({
    tagName: 'dda-accordion',
    elementClass: DdaAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaAccordionEvents,
    defineCustomElement: defineDdaAccordion
});

type DdaAlertEvents = {
    onFirstClick: EventName<CustomEvent<void>>,
    onSecondClick: EventName<CustomEvent<void>>
};

export const DdaAlert: StencilReactComponent<DdaAlertElement, DdaAlertEvents> = /*@__PURE__*/ createComponent<DdaAlertElement, DdaAlertEvents>({
    tagName: 'dda-alert',
    elementClass: DdaAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onFirstClick: 'firstClick',
        onSecondClick: 'secondClick'
    } as DdaAlertEvents,
    defineCustomElement: defineDdaAlert
});

type DdaAttachFileEvents = NonNullable<unknown>;

export const DdaAttachFile: StencilReactComponent<DdaAttachFileElement, DdaAttachFileEvents> = /*@__PURE__*/ createComponent<DdaAttachFileElement, DdaAttachFileEvents>({
    tagName: 'dda-attach-file',
    elementClass: DdaAttachFileElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaAttachFileEvents,
    defineCustomElement: defineDdaAttachFile
});

type DdaAvatarEvents = NonNullable<unknown>;

export const DdaAvatar: StencilReactComponent<DdaAvatarElement, DdaAvatarEvents> = /*@__PURE__*/ createComponent<DdaAvatarElement, DdaAvatarEvents>({
    tagName: 'dda-avatar',
    elementClass: DdaAvatarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaAvatarEvents,
    defineCustomElement: defineDdaAvatar
});

type DdaBannerEvents = NonNullable<unknown>;

export const DdaBanner: StencilReactComponent<DdaBannerElement, DdaBannerEvents> = /*@__PURE__*/ createComponent<DdaBannerElement, DdaBannerEvents>({
    tagName: 'dda-banner',
    elementClass: DdaBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaBannerEvents,
    defineCustomElement: defineDdaBanner
});

type DdaBreadcrumbEvents = NonNullable<unknown>;

export const DdaBreadcrumb: StencilReactComponent<DdaBreadcrumbElement, DdaBreadcrumbEvents> = /*@__PURE__*/ createComponent<DdaBreadcrumbElement, DdaBreadcrumbEvents>({
    tagName: 'dda-breadcrumb',
    elementClass: DdaBreadcrumbElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaBreadcrumbEvents,
    defineCustomElement: defineDdaBreadcrumb
});

type DdaButtonEvents = NonNullable<unknown>;

export const DdaButton: StencilReactComponent<DdaButtonElement, DdaButtonEvents> = /*@__PURE__*/ createComponent<DdaButtonElement, DdaButtonEvents>({
    tagName: 'dda-button',
    elementClass: DdaButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaButtonEvents,
    defineCustomElement: defineDdaButton
});

type DdaCheckboxEvents = NonNullable<unknown>;

export const DdaCheckbox: StencilReactComponent<DdaCheckboxElement, DdaCheckboxEvents> = /*@__PURE__*/ createComponent<DdaCheckboxElement, DdaCheckboxEvents>({
    tagName: 'dda-checkbox',
    elementClass: DdaCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaCheckboxEvents,
    defineCustomElement: defineDdaCheckbox
});

type DdaChipEvents = NonNullable<unknown>;

export const DdaChip: StencilReactComponent<DdaChipElement, DdaChipEvents> = /*@__PURE__*/ createComponent<DdaChipElement, DdaChipEvents>({
    tagName: 'dda-chip',
    elementClass: DdaChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaChipEvents,
    defineCustomElement: defineDdaChip
});

type DdaCreditCardEvents = NonNullable<unknown>;

export const DdaCreditCard: StencilReactComponent<DdaCreditCardElement, DdaCreditCardEvents> = /*@__PURE__*/ createComponent<DdaCreditCardElement, DdaCreditCardEvents>({
    tagName: 'dda-credit-card',
    elementClass: DdaCreditCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaCreditCardEvents,
    defineCustomElement: defineDdaCreditCard
});

type DdaCreditcardFieldEvents = NonNullable<unknown>;

export const DdaCreditcardField: StencilReactComponent<DdaCreditcardFieldElement, DdaCreditcardFieldEvents> = /*@__PURE__*/ createComponent<DdaCreditcardFieldElement, DdaCreditcardFieldEvents>({
    tagName: 'dda-creditcard-field',
    elementClass: DdaCreditcardFieldElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaCreditcardFieldEvents,
    defineCustomElement: defineDdaCreditcardField
});

type DdaDropdownEvents = NonNullable<unknown>;

export const DdaDropdown: StencilReactComponent<DdaDropdownElement, DdaDropdownEvents> = /*@__PURE__*/ createComponent<DdaDropdownElement, DdaDropdownEvents>({
    tagName: 'dda-dropdown',
    elementClass: DdaDropdownElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaDropdownEvents,
    defineCustomElement: defineDdaDropdown
});

type DdaFooterEvents = NonNullable<unknown>;

export const DdaFooter: StencilReactComponent<DdaFooterElement, DdaFooterEvents> = /*@__PURE__*/ createComponent<DdaFooterElement, DdaFooterEvents>({
    tagName: 'dda-footer',
    elementClass: DdaFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaFooterEvents,
    defineCustomElement: defineDdaFooter
});

type DdaHeaderEvents = {
    onLanguageSwitch: EventName<CustomEvent<void>>,
    onSmTextSize: EventName<CustomEvent<void>>,
    onBaseTextSize: EventName<CustomEvent<void>>,
    onLgTextSize: EventName<CustomEvent<void>>,
    onNormalContrast: EventName<CustomEvent<void>>,
    onBlindContrast: EventName<CustomEvent<void>>,
    onRedContrast: EventName<CustomEvent<void>>,
    onGreenContrast: EventName<CustomEvent<void>>
};

export const DdaHeader: StencilReactComponent<DdaHeaderElement, DdaHeaderEvents> = /*@__PURE__*/ createComponent<DdaHeaderElement, DdaHeaderEvents>({
    tagName: 'dda-header',
    elementClass: DdaHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onLanguageSwitch: 'languageSwitch',
        onSmTextSize: 'smTextSize',
        onBaseTextSize: 'baseTextSize',
        onLgTextSize: 'lgTextSize',
        onNormalContrast: 'normalContrast',
        onBlindContrast: 'blindContrast',
        onRedContrast: 'redContrast',
        onGreenContrast: 'greenContrast'
    } as DdaHeaderEvents,
    defineCustomElement: defineDdaHeader
});

type DdaHomeBannerEvents = NonNullable<unknown>;

export const DdaHomeBanner: StencilReactComponent<DdaHomeBannerElement, DdaHomeBannerEvents> = /*@__PURE__*/ createComponent<DdaHomeBannerElement, DdaHomeBannerEvents>({
    tagName: 'dda-home-banner',
    elementClass: DdaHomeBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaHomeBannerEvents,
    defineCustomElement: defineDdaHomeBanner
});

type DdaHorizontalStepperEvents = NonNullable<unknown>;

export const DdaHorizontalStepper: StencilReactComponent<DdaHorizontalStepperElement, DdaHorizontalStepperEvents> = /*@__PURE__*/ createComponent<DdaHorizontalStepperElement, DdaHorizontalStepperEvents>({
    tagName: 'dda-horizontal-stepper',
    elementClass: DdaHorizontalStepperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaHorizontalStepperEvents,
    defineCustomElement: defineDdaHorizontalStepper
});

type DdaInputEvents = NonNullable<unknown>;

export const DdaInput: StencilReactComponent<DdaInputElement, DdaInputEvents> = /*@__PURE__*/ createComponent<DdaInputElement, DdaInputEvents>({
    tagName: 'dda-input',
    elementClass: DdaInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaInputEvents,
    defineCustomElement: defineDdaInput
});

type DdaLinkButtonEvents = NonNullable<unknown>;

export const DdaLinkButton: StencilReactComponent<DdaLinkButtonElement, DdaLinkButtonEvents> = /*@__PURE__*/ createComponent<DdaLinkButtonElement, DdaLinkButtonEvents>({
    tagName: 'dda-link-button',
    elementClass: DdaLinkButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaLinkButtonEvents,
    defineCustomElement: defineDdaLinkButton
});

type DdaNumberFieldEvents = NonNullable<unknown>;

export const DdaNumberField: StencilReactComponent<DdaNumberFieldElement, DdaNumberFieldEvents> = /*@__PURE__*/ createComponent<DdaNumberFieldElement, DdaNumberFieldEvents>({
    tagName: 'dda-number-field',
    elementClass: DdaNumberFieldElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaNumberFieldEvents,
    defineCustomElement: defineDdaNumberField
});

type DdaPaginationEvents = NonNullable<unknown>;

export const DdaPagination: StencilReactComponent<DdaPaginationElement, DdaPaginationEvents> = /*@__PURE__*/ createComponent<DdaPaginationElement, DdaPaginationEvents>({
    tagName: 'dda-pagination',
    elementClass: DdaPaginationElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaPaginationEvents,
    defineCustomElement: defineDdaPagination
});

type DdaPhonefieldEvents = NonNullable<unknown>;

export const DdaPhonefield: StencilReactComponent<DdaPhonefieldElement, DdaPhonefieldEvents> = /*@__PURE__*/ createComponent<DdaPhonefieldElement, DdaPhonefieldEvents>({
    tagName: 'dda-phonefield',
    elementClass: DdaPhonefieldElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaPhonefieldEvents,
    defineCustomElement: defineDdaPhonefield
});

type DdaProgressbarEvents = NonNullable<unknown>;

export const DdaProgressbar: StencilReactComponent<DdaProgressbarElement, DdaProgressbarEvents> = /*@__PURE__*/ createComponent<DdaProgressbarElement, DdaProgressbarEvents>({
    tagName: 'dda-progressbar',
    elementClass: DdaProgressbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaProgressbarEvents,
    defineCustomElement: defineDdaProgressbar
});

type DdaRadiobuttonEvents = NonNullable<unknown>;

export const DdaRadiobutton: StencilReactComponent<DdaRadiobuttonElement, DdaRadiobuttonEvents> = /*@__PURE__*/ createComponent<DdaRadiobuttonElement, DdaRadiobuttonEvents>({
    tagName: 'dda-radiobutton',
    elementClass: DdaRadiobuttonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaRadiobuttonEvents,
    defineCustomElement: defineDdaRadiobutton
});

type DdaRangeSliderEvents = NonNullable<unknown>;

export const DdaRangeSlider: StencilReactComponent<DdaRangeSliderElement, DdaRangeSliderEvents> = /*@__PURE__*/ createComponent<DdaRangeSliderElement, DdaRangeSliderEvents>({
    tagName: 'dda-range-slider',
    elementClass: DdaRangeSliderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaRangeSliderEvents,
    defineCustomElement: defineDdaRangeSlider
});

type DdaSearchInputEvents = NonNullable<unknown>;

export const DdaSearchInput: StencilReactComponent<DdaSearchInputElement, DdaSearchInputEvents> = /*@__PURE__*/ createComponent<DdaSearchInputElement, DdaSearchInputEvents>({
    tagName: 'dda-search-input',
    elementClass: DdaSearchInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaSearchInputEvents,
    defineCustomElement: defineDdaSearchInput
});

type DdaSegmentedTabsEvents = NonNullable<unknown>;

export const DdaSegmentedTabs: StencilReactComponent<DdaSegmentedTabsElement, DdaSegmentedTabsEvents> = /*@__PURE__*/ createComponent<DdaSegmentedTabsElement, DdaSegmentedTabsEvents>({
    tagName: 'dda-segmented-tabs',
    elementClass: DdaSegmentedTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaSegmentedTabsEvents,
    defineCustomElement: defineDdaSegmentedTabs
});

type DdaSelectEvents = NonNullable<unknown>;

export const DdaSelect: StencilReactComponent<DdaSelectElement, DdaSelectEvents> = /*@__PURE__*/ createComponent<DdaSelectElement, DdaSelectEvents>({
    tagName: 'dda-select',
    elementClass: DdaSelectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaSelectEvents,
    defineCustomElement: defineDdaSelect
});

type DdaStickyFooterEvents = NonNullable<unknown>;

export const DdaStickyFooter: StencilReactComponent<DdaStickyFooterElement, DdaStickyFooterEvents> = /*@__PURE__*/ createComponent<DdaStickyFooterElement, DdaStickyFooterEvents>({
    tagName: 'dda-sticky-footer',
    elementClass: DdaStickyFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaStickyFooterEvents,
    defineCustomElement: defineDdaStickyFooter
});

type DdaTabsEvents = { onTabClick: EventName<CustomEvent<void>> };

export const DdaTabs: StencilReactComponent<DdaTabsElement, DdaTabsEvents> = /*@__PURE__*/ createComponent<DdaTabsElement, DdaTabsEvents>({
    tagName: 'dda-tabs',
    elementClass: DdaTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onTabClick: 'tabClick' } as DdaTabsEvents,
    defineCustomElement: defineDdaTabs
});

type DdaTextareaEvents = NonNullable<unknown>;

export const DdaTextarea: StencilReactComponent<DdaTextareaElement, DdaTextareaEvents> = /*@__PURE__*/ createComponent<DdaTextareaElement, DdaTextareaEvents>({
    tagName: 'dda-textarea',
    elementClass: DdaTextareaElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaTextareaEvents,
    defineCustomElement: defineDdaTextarea
});

type DdaToggleEvents = NonNullable<unknown>;

export const DdaToggle: StencilReactComponent<DdaToggleElement, DdaToggleEvents> = /*@__PURE__*/ createComponent<DdaToggleElement, DdaToggleEvents>({
    tagName: 'dda-toggle',
    elementClass: DdaToggleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaToggleEvents,
    defineCustomElement: defineDdaToggle
});

type DdaTooltipEvents = NonNullable<unknown>;

export const DdaTooltip: StencilReactComponent<DdaTooltipElement, DdaTooltipEvents> = /*@__PURE__*/ createComponent<DdaTooltipElement, DdaTooltipEvents>({
    tagName: 'dda-tooltip',
    elementClass: DdaTooltipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaTooltipEvents,
    defineCustomElement: defineDdaTooltip
});

type DdaUiCardEvents = { onLinkClick: EventName<CustomEvent<void>> };

export const DdaUiCard: StencilReactComponent<DdaUiCardElement, DdaUiCardEvents> = /*@__PURE__*/ createComponent<DdaUiCardElement, DdaUiCardEvents>({
    tagName: 'dda-ui-card',
    elementClass: DdaUiCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onLinkClick: 'linkClick' } as DdaUiCardEvents,
    defineCustomElement: defineDdaUiCard
});

type DdaVerticalStepperEvents = NonNullable<unknown>;

export const DdaVerticalStepper: StencilReactComponent<DdaVerticalStepperElement, DdaVerticalStepperEvents> = /*@__PURE__*/ createComponent<DdaVerticalStepperElement, DdaVerticalStepperEvents>({
    tagName: 'dda-vertical-stepper',
    elementClass: DdaVerticalStepperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DdaVerticalStepperEvents,
    defineCustomElement: defineDdaVerticalStepper
});
