
import * as d from './components';

export const DIRECTIVES = [
  d.DdaAccordion,
  d.DdaAlert,
  d.DdaAttachFile,
  d.DdaAvatar,
  d.DdaBanner,
  d.DdaBreadcrumb,
  d.DdaButton,
  d.DdaCheckbox,
  d.DdaChip,
  d.DdaCreditCard,
  d.DdaCreditcardField,
  d.DdaDropdown,
  d.DdaFooter,
  d.DdaHeader,
  d.DdaHomeBanner,
  d.DdaHorizontalStepper,
  d.DdaInput,
  d.DdaLinkButton,
  d.DdaNumberField,
  d.DdaPagination,
  d.DdaPhonefield,
  d.DdaProgressbar,
  d.DdaRadiobutton,
  d.DdaRangeSlider,
  d.DdaSearchInput,
  d.DdaSegmentedTabs,
  d.DdaSelect,
  d.DdaStickyFooter,
  d.DdaTabs,
  d.DdaTextarea,
  d.DdaToggle,
  d.DdaTooltip,
  d.DdaUiCard,
  d.DdaVerticalStepper
];
